### ISSUE TITLE
Add option to stop showing snow.

### ISSUE THREAD

**Issue by aciccarello** [erikwatson/snowfall.js#28]
I'd like to have a button where the user can stop the snow animation but there is no method to do so. My current workaround is to set gravity to zero. However this isn't perfect because running start again will cause the snow to fall with a higher gravity version than expected.

**Comment by aciccarello** [comment]
Thanks for adding that. I just took a look and the [minified release](https://cdn.jsdelivr.net/npm/@erikwatson/snowfall/dist/snowfall.min.js) on npm seems to be missing the new methods.

**Comment by erikwatson** [comment]
Oh man, so sorry @aciccarello! I have corrected that now, do let me know if you have any other problems with it.

**Comment by aciccarello** [comment]
That worked great! Thanks!
